/** Tăng version khi thay đổi permission hoặc quyền của role hệ thống. */
export const ACCESS_CONTROL_VERSION = 1;

export const SYSTEM_PERMISSIONS = [
  "user.read",
  "user.create",
  "user.update",
  "user.deactivate",
  "user.reset_password",
  "user.revoke_sessions",
  "role.read",
  "role.manage",
  "grant.read",
  "grant.assign",
  "grant.revoke",
  "facility.read",
  "facility.manage",
  "stock_location.read",
  "stock_location.manage",
  "department.read",
  "department.manage",
  "ingredient.read",
  "ingredient.manage",
  "ingredient_group.manage",
  "unit.read",
  "unit.manage",
  "conversion.read",
  "conversion.manage",
  "supplier.read",
  "supplier.manage",
  "supplier_ingredient.read",
  "supplier_ingredient.manage",
  "eligibility.read",
  "eligibility.manage",
  "source_rule.read",
  "source_rule.manage",
  "source_rule.bulk_update",
  "request.read",
  "request.create",
  "request.update_draft",
  "request.revise",
  "request.submit",
  "request.cancel",
  "request.approve",
  "request.reject",
  "order.read",
  "order.release",
  "order.export",
  "order.change_source",
  "order.close_outstanding",
  "order.cancel",
  "transfer.read",
  "transfer.create",
  "transfer.update_draft",
  "transfer.submit",
  "transfer.approve",
  "transfer.reject",
  "transfer.cancel",
  "dispatch.read",
  "dispatch.create",
  "dispatch.post",
  "receipt.read",
  "receipt.create",
  "receipt.post",
  "discrepancy.read",
  "discrepancy.resolve",
  "stock.read",
  "stock_ledger.read",
  "adjustment.read",
  "adjustment.create",
  "adjustment.approve",
  "adjustment.post",
  "stocktake.read",
  "stocktake.create",
  "stocktake.update_draft",
  "stocktake.submit",
  "stocktake.reopen",
  "damage.create",
  "damage.read",
  "damage.update_draft",
  "damage.submit",
  "damage.confirm",
  "variance.read",
  "variance.recalculate",
  "alert_rule.manage",
  "recipe.read",
  "recipe.manage",
  "ipos_mapping.read",
  "ipos_mapping.manage",
  "sales_import.create",
  "sales_import.read",
  "sales_import.commit",
  "payment_tracking.read",
  "payment_tracking.update",
  "report.stock",
  "report.fulfillment",
  "report.variance",
  "report.damage",
  "report.payment",
  "report.export",
  "audit.read",
  "attachment.upload",
  "notification.read_own",
  "notification.mark_own",
  "backup.manage",
  "supplier_order.read_own",
  "dashboard.read",
] as const;

export const SYSTEM_ROLE_PERMISSIONS: Record<string, readonly string[]> = {
  ADMIN_OWNER: SYSTEM_PERMISSIONS.filter(
    (permission) =>
      permission !== "backup.manage" &&
      permission !== "supplier_order.read_own",
  ),
  GENERAL_MANAGER: SYSTEM_PERMISSIONS.filter(
    (permission) =>
      ![
        "role.manage",
        "grant.assign",
        "grant.revoke",
        "backup.manage",
        "supplier_order.read_own",
        "sales_import.commit",
      ].includes(permission),
  ),
  BRANCH_MANAGER: [
    "facility.read",
    "stock_location.read",
    "department.read",
    "ingredient.read",
    "unit.read",
    "supplier.read",
    "eligibility.read",
    "source_rule.read",
    "request.read",
    "request.create",
    "request.update_draft",
    "request.revise",
    "request.submit",
    "request.cancel",
    "order.read",
    "receipt.read",
    "receipt.create",
    "receipt.post",
    "stock.read",
    "stocktake.read",
    "stocktake.create",
    "stocktake.update_draft",
    "stocktake.submit",
    "damage.create",
    "damage.read",
    "notification.read_own",
    "notification.mark_own",
    "dashboard.read",
  ],
  BRANCH_STAFF: [
    "facility.read",
    "stock_location.read",
    "department.read",
    "ingredient.read",
    "unit.read",
    "eligibility.read",
    "source_rule.read",
    "request.read",
    "request.create",
    "request.update_draft",
    "request.revise",
    "request.submit",
    "request.cancel",
    "order.read",
    "receipt.read",
    "receipt.create",
    "receipt.post",
    "stock.read",
    "stocktake.read",
    "stocktake.create",
    "stocktake.update_draft",
    "stocktake.submit",
    "damage.create",
    "damage.update_draft",
    "damage.submit",
    "notification.read_own",
    "notification.mark_own",
    "dashboard.read",
  ],
  WAREHOUSE_STAFF: [
    "facility.read",
    "stock_location.read",
    "department.read",
    "ingredient.read",
    "unit.read",
    "supplier.read",
    "supplier_ingredient.read",
    "eligibility.read",
    "source_rule.read",
    "request.read",
    "request.create",
    "request.update_draft",
    "request.revise",
    "request.submit",
    "request.cancel",
    "order.read",
    "dispatch.read",
    "dispatch.create",
    "dispatch.post",
    "receipt.read",
    "receipt.create",
    "receipt.post",
    "stock.read",
    "stock_ledger.read",
    "stocktake.read",
    "stocktake.create",
    "stocktake.update_draft",
    "stocktake.submit",
    "damage.create",
    "damage.update_draft",
    "damage.submit",
    "notification.read_own",
    "notification.mark_own",
    "dashboard.read",
  ],
  SUPPLIER: [
    "supplier_order.read_own",
    "notification.read_own",
    "notification.mark_own",
  ],
};

export const SYSTEM_ROLE_NAMES: Record<string, string> = {
  ADMIN_OWNER: "Quản trị hệ thống",
  GENERAL_MANAGER: "Quản lý tổng",
  BRANCH_MANAGER: "Quản lý chi nhánh",
  BRANCH_STAFF: "Nhân viên chi nhánh",
  WAREHOUSE_STAFF: "Nhân viên kho",
  SUPPLIER: "Nhà cung cấp",
};
